src/main/java/com/utils/Beans/HistorialBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utils.Beans;

import com.utils.Entities.HistorialEntity;
import com.utils.Entities.UsuariosEntity;
import com.utils.Model.HistorialModel;
import java.io.IOException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;

/**
 *
 * @author Ernesto
 */
@Named(value = "historialBean")
@SessionScoped
public class HistorialBean implements Serializable {

    @EJB
    private HistorialModel historialModel;
    private HistorialEntity historial = new HistorialEntity();
    private List<HistorialEntity> listaHistorial;

    /**
     * Creates a new instance of HistorialBean
     */
    public HistorialBean() {

    }

    @PostConstruct
    public void init() {
//        historialdelUsuario = historialModel.listarHistorialporUsuario(LoginBean.usuario_en_sesion);

    }

    /**
     * @return the historialdelUsuario
     */
    public List<HistorialEntity> listarHistorialUsuario(UsuariosEntity usuario) {
        
        listaHistorial = historialModel.listarHistorialporUsuario(usuario);
        if (!historial.getBusqueda().trim().equals("")) {
            System.out.print("Esta buscando: " + historial.getBusqueda());
            listaHistorial = historialModel.listarHistorialporNombre(historial.getBusqueda(), usuario);
        } else if (historial.getFechaHora() != null) {
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String fechaString = formatter.format(historial.getFechaHora());
            System.out.print("Fecha   ->: " + fechaString);
            System.out.print("Usuario ->: " + usuario.getIdUsuario());
            System.out.print("Esta buscando la fecha: " + historial.getFechaHora());
             listaHistorial = historialModel.listarHistorialporFecha(fechaString, usuario.getIdUsuario());
        }
        //Limpiamos propiedades
        //historial.setBusqueda("");
        //historial.setFechaHora(null);
        return listaHistorial;
    }

//    public void listarporNombre() {
//        if (historial.getBusqueda().trim().equals("")) {
//            historialdelUsuario = historialModel.listarHistorialporUsuario(LoginBean.usuario_en_sesion);
//        } else {
//            System.out.print("Esta buscando: " + historial.getBusqueda());
//            historialdelUsuario = historialModel.listarHistorialporNombre(historial.getBusqueda());
//
//        }
//
//    }
    
    
    public void redireccion() throws IOException{
        FacesContext.getCurrentInstance().getExternalContext().redirect("../search/productos.xhtml");
    }
    /**
     * @return the historial
     */
    public HistorialEntity getHistorial() {
        return historial;
    }

    /**
     * @param historial the historial to set
     */
    public void setHistorial(HistorialEntity historial) {
        this.historial = historial;
    }

    public void listarporFecha(UsuariosEntity usuario){
            
        if(historial.getFechaHora()==null){
             listaHistorial = historialModel.listarHistorialporUsuario(usuario);
        }else{
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String fechaString = formatter.format(historial.getFechaHora());
            System.out.print("Fecha   ->: " + fechaString);
            System.out.print("Usuario ->: " + usuario.getIdUsuario());
            
            System.out.print("Esta buscando la fecha: " + historial.getFechaHora());
             listaHistorial = historialModel.listarHistorialporFecha(fechaString, usuario.getIdUsuario());
            
        }
        
    } 
    
}

src/main/java/com/utils/Beans/UsuarioBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utils.Beans;

import com.utils.Entities.TipoUsuariosEntity;
import com.utils.Entities.UsuariosEntity;
import com.utils.Model.UsuarioModel;
import com.utils.Utils.jsfUtil;
import com.utils.Utils.validation;
import java.io.IOException;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import org.primefaces.model.chart.PieChartModel;

/**
 *
 * @author Jonathan
 */
@Named(value = "usuarioBean")
@SessionScoped
public class UsuarioBean implements Serializable {

    @EJB
    private UsuarioModel usuarioModel;
    private UsuariosEntity usuario = new UsuariosEntity();
    List<UsuariosEntity> listaUsuarios;
    private String nuevaContra = "";
    //private String confirmar = "";
    private PieChartModel pastelModel1;
    private PieChartModel pastelModel2;

    public UsuarioBean() {
    }

    @PostConstruct
    public void init() {
        graficoEdades();
        graficoGenero();
    }

    public List<UsuariosEntity> getListaUsuarios() {
        listaUsuarios = usuarioModel.listarUsuarios();
        return listaUsuarios;
    }

    public String insertarUsuario() {
        TipoUsuariosEntity tipo = new TipoUsuariosEntity();
        tipo.setId(3);
        usuario.setTipoUsuario(tipo);
        usuario.setIdUsuario(validation.Code(usuario.getNombres(), usuario.getApellidos()));
        usuario.setPassword(validation.getMD5(usuario.getPassword()));

        if (usuarioModel.agregarUsuario(this.usuario) > 0) {
            FacesContext.getCurrentInstance().getExternalContext().getFlash().put("exito", "Fuiste registrado exitosamente");
            return "iniciar?faces-redirect=true";
        } else {
            FacesContext.getCurrentInstance().getExternalContext().getFlash().put("error", "Este correo ya fue registrado");
            return null;
        }
    }

    public String modificarUsuario() {

        if (!nuevaContra.isEmpty()) {
            usuario.setPassword(validation.getMD5(nuevaContra));
        }

        if (usuarioModel.modificarUsuario(usuario) > 0) {
            //FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Registrado exitosamente!"));
            FacesContext.getCurrentInstance().getExternalContext().getFlash().put("success", "Fuiste registrado exitosamente");
            usuario = new UsuariosEntity();
            return "/cliente/dashboardClient?faces-redirect=true";
        } else {
            FacesContext.getCurrentInstance().getExternalContext().getFlash().put("error", "Este correo ya fue registrado");
            return "/cliente/UserDate?faces-redirect=true";
        }
    }

    public void graficoGenero() {
        pastelModel1 = new PieChartModel();
        pastelModel1.set("Hombres", usuarioModel.cantidadUsuariosGenero('m'));
        pastelModel1.set("Mujeres", usuarioModel.cantidadUsuariosGenero('f'));
        pastelModel1.setTitle("Porcentaje de usuarios hombres y mujeres");
        pastelModel1.setLegendPosition("no");
        pastelModel1.setShowDataLabels(true);
        pastelModel1.setDiameter(300);
        pastelModel1.setShadow(false);
    }

    public void graficoEdades() {
        List<Long> edades = usuarioModel.obtenerEdadesUsuarios();
        pastelModel2 = new PieChartModel();
        int n1 = 0;
        int n2 = 0;
        int n3 = 0;
        int n4 = 0;
        int n5 = 0;
        for (Long edad : edades) {
            if (edad >= 0 && edad <= 12) {
                n1++;
            } else if (edad >= 13 && edad <= 17) {
                n2++;
            } else if (edad >= 18 && edad <= 29) {
                n3++;
            } else if (edad >= 30 && edad <= 59) {
                n4++;
            } else {
                n5++;
            }
        }

        pastelModel2.set("Niños (0-12) años", n1);
        pastelModel2.set("Adolescentes (13-17) años", n2);
        pastelModel2.set("Adulto Jóven (18-29) años", n3);
        pastelModel2.set("Adultos (30-59) años", n4);
        pastelModel2.set("Adulto Mayor (60 + ) años", n5);
        pastelModel2.setTitle("Porcentaje de edades de usuarios");
        pastelModel2.setLegendPosition("se");
        pastelModel2.setShowDataLabels(true);
        pastelModel2.setDiameter(250);
        pastelModel2.setShadow(false);
    }

    public String obtenerUsuario(String codigo) {
        usuario = usuarioModel.buscarUsuario(codigo);
        return "/dashboard/registrarAdmin?faces-redirect=true";
    }

    public void obtenerUsuariodeBusqueda(String codigo) {
        usuario = usuarioModel.buscarUsuario(codigo);

    }

    public void obtenerUsuarioSesion(String codigo) throws IOException {
        usuario = usuarioModel.buscarUsuario(codigo);
        FacesContext.getCurrentInstance().getExternalContext().redirect("../cliente/UserDate.xhtml");
    }

    public String eliminarUsuario(String codigo) {

        if (usuarioModel.eliminarUsuario(codigo) > 0) {

        }

        return null;
    }

    public Date getFechaActual() {
        return new Date();
    }

    public UsuariosEntity getUsuario() {
        return usuario;
    }

    public void setUsuario(UsuariosEntity usuario) {
        this.usuario = usuario;
    }

    public String getNuevaContra() {
        return nuevaContra;
    }

    public void setNuevaContra(String nuevaContra) {
        this.nuevaContra = nuevaContra;
    }

    public PieChartModel getPastelModel1() {
        return pastelModel1;
    }

    public void setPastelModel1(PieChartModel pastelModel1) {
        this.pastelModel1 = pastelModel1;
    }

    public PieChartModel getPastelModel2() {
        return pastelModel2;
    }

    public void setPastelModel2(PieChartModel pastelModel2) {
        this.pastelModel2 = pastelModel2;
    }

}

src/main/webapp/usuarios/dashboard.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/dashboard-layout-base.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="titulo">
        Dashboard - Utils.do
    </ui:define>

    <ui:define name="contenido">
        #{loginBean.security(3)}
         <p:growl showDetail="true" globalOnly="true"/>
        <!-- End Navbar -->
        <div class="panel-header panel-header-sm"></div>
        <div class="content">
            <div class="row">
                <div class="col-md-4">
                    <div class="card  card-tasks">
                        <div class="card-header ">
                            <h5 class="card-category">Listas</h5>
                            <h4 class="card-title">Agregar nueva lista</h4>
                        </div>
                        <div class="card-body ">
                            <div class="table-full-width table-responsive">
                                <h:form>
                                    <h:outputLabel value="Nombre de la lista:" for="nombre" />
                                    <h:inputText id="nombre" value="#{listaBean.lista.nombre}" title="Nombre" required="true" requiredMessage="El campo es re requerido"/>
                                    <h:commandButton styleClass="btn btn-default" action="#{listaBean.insertarLista(loginBean.usuario.idUsuario)}" value="Agregar"></h:commandButton>
                                </h:form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-category">Lista</h5>
                            <h4 class="card-title">Listas creadas</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <h:form>
                                    <h:dataTable class="table" value="#{listaBean.getListaListas(loginBean.usuario.idUsuario)}" var="item">
                                        <h:column>
                                            <f:facet name="header">
                                                <h:outputText class=" text-primary" value="Código"/>
                                            </f:facet>
                                            <h:outputText value="#{item.idLista}"/>
                                        </h:column>
                                        <h:column>
                                            <f:facet name="header">
                                                <h:outputText class=" text-primary" value="Nombre"/>
                                            </f:facet>
                                            <h:outputText  value="#{item.nombre}"/>
                                        </h:column>
                                        <h:column>
                                            <f:facet name="header">
                                                <h:outputText class=" text-primary" value="Opción 1"/>
                                            </f:facet>
                                            <h:commandButton styleClass="btn btn-info" value="Modificar"></h:commandButton>
                                        </h:column>
                                        <h:column>
                                            <f:facet name="header">
                                                <h:outputText class=" text-primary" value="Opción 2"/>
                                            </f:facet>

                                            <h:commandButton styleClass="btn btn-dark" value="Ver detalles"></h:commandButton>
                                        </h:column>
                                        <h:column>
                                            <f:facet name="header">
                                                <h:outputText class=" text-primary" value="Opción 3"/>
                                            </f:facet>          
                                            <h:commandButton onclick="return confirma();" styleClass="btn btn-danger" action="#{listaBean.eliminarLista(item.idLista)}" value="Eliminar"></h:commandButton>
                                        </h:column>
                                    </h:dataTable>
                                </h:form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>

    <ui:define name="scripts">
        <h:outputScript>
            function confirma(){
            return alertify.dialog('confirm');
            }
        </h:outputScript>
    </ui:define>

</ui:composition>

src/main/webapp/usuarios/historial.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/dashboard-layout-base.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <ui:define name="titulo">
        Historial de Búsqueda - Utils.do
    </ui:define>

    <ui:define name="contenido">
        #{loginBean.sesionRequerida()}
        <!-- End Navbar -->
        <div class="panel-header panel-header-sm"></div>
        <div class="content">
            <div class="row">
                <div class="col-md-4">
                    <div class="card  card-tasks">
                        <div class="card-header ">
                            <h5 class="card-category">Buscar en historial</h5>
                            <h4 class="card-title">Filtrar Historial por:</h4>
                        </div>
                        <div class="card-body ">
                            <div class="table-full-width table-responsive">
                                <h:form id="busquedaForm">
                                    <h:outputLabel value="Nombre:" for="nombre" />
                                    <br />
                                    <h:inputText value="#{historialBean.historial.busqueda}">
                                        <!--<f:ajax listener="" render="tablaHistorial" event="keydown"/>-->
                                        <f:ajax listener="#{historialBean.listarHistorialUsuario(loginBean.usuario)}" render="tablaHistorial" event="keydown"/>
                                    </h:inputText>
                                    <br />

                                </h:form>
                                <h:form id="fechaForm">
                                    <div class="form-group">
                                        <label for="fechaNacimiento">Fecha de búsqueda:</label>
                                        <div class="space-10"></div>
                                        <p:datePicker  id="fecha" value="#{historialBean.historial.fechaHora}" required="true" requiredMessage="Indique una fecha de búsqueda" showIcon="true" maxdate="#{usuarioBean.fechaActual}" pattern="yyyy-MM-dd">
                                            <p:ajax  event="dateSelect" listener="#{historialBean.listarporFecha(loginBean.usuario)}" update="tablaHistorial"/>
                                        </p:datePicker>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-10"></div>
                                        <div class="space-50"></div>
                                        <h:message for="fecha" style="color:red"></h:message>
                                    </div>
                                </h:form>
                                <div class="space-10"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-category">Historial de búsqueda</h5>
                            <h4 class="card-title">Historial de búsqueda</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <h:form prependId="false">
                                    <p:dataTable class="table" value="#{historialBean.listarHistorialUsuario(loginBean.usuario)}" var="item" id="tablaHistorial"
                                                 rows="5" paginator="true" paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}" 
                                                 rowsPerPageTemplate="5,10,15" styleClass="table table-bordered table-striped">
                                        <p:column headerText="Búsqueda realizada">
                                            <h:commandLink action="#{historialBean.redireccion()}" value="#{item.busqueda}"/>
                                        </p:column>
                                        <p:column headerText="Fecha y Hora">
                                            <h:outputText value="#{item.fechaHora}">
                                                <f:convertDateTime pattern="dd/MM/yyyy - HH:mm" />
                                            </h:outputText>
                                        </p:column>
                                    </p:dataTable>
                                </h:form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>

    <ui:define name="scripts">
        <h:outputScript library="js" name="jquery.magnific-popup.js" />
        <h:outputScript library="js" name='jquery.nice-select.min.js'/>
    </ui:define>
</ui:composition>

src/main/webapp/usuarios/registrate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="../WEB-INF/landig-layout-base.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="titulo">
        Registrate - Utils.do
    </ui:define>

    <ui:define name="contenido">
        <br></br>
        <!-- learning part start-->
        <section class="learning_part pb-5 pt-5">
            <div class="container">
                <div class="row align-items-sm-center align-items-lg-stretch">
                    <div class="col-md-7 col-lg-7">

                        <div class="learning_img">
                            <h1 class="text-center" ></h1>
                            <img src="../resources/img/learning_img.png" alt=""/>
                        </div>
                    </div>
                    <div class="col-md-5 col-lg-5 pt-3 px-4 shadow-sm mt-5">
                        <div class="learning_member_text mb-2">
                            <h5>Utils.do</h5>
                            <h2>Regístrate</h2>

                            <h:form id="registroForm">
                                <div class="form-group">
                                    <label for="name">Nombres:</label>
                                    <h:inputText validatorMessage="Ingrese un nombre válido" pt:placeholder="Nombres" id="name" styleClass="single-input-secondary" value="#{usuarioBean.usuario.nombres}" required="true" requiredMessage="Ingrese sus nombres">
                                        <f:validateRegex pattern="[A-Za-zÁÉÍÓÚñáéíóúÑ ]{1,}"></f:validateRegex>
                                    </h:inputText>
                                    <h:message for="name" style="color:red"></h:message>
                                </div>
                                <div class="form-group">
                                    <label for="lastname">Apellidos:</label>
                                    <h:inputText validatorMessage="Ingrese un apellido válido" pt:placeholder="Apellidos" id="lastName" styleClass="single-input-secondary" value="#{usuarioBean.usuario.apellidos}" required="true" requiredMessage="Ingrese sus apellidos">
                                        <f:validateRegex pattern="[A-Za-zÁÉÍÓÚñáéíóúÑ ]{1,}"></f:validateRegex>
                                    </h:inputText>
                                    <h:message for="lastName" style="color:red"></h:message>
                                </div>
                                <div class="form-group">
                                    <label for="genero">Género:</label>
                                    <div class="form-select" id="default-select">
                                        <h:selectOneMenu  styleClass="single-input-secondary" id="genero" required="true" requiredMessage="Indique su género por favor" value="#{usuarioBean.usuario.sexo}">
                                            <f:selectItem itemValue="m" itemLabel="Masculino"/>
                                            <f:selectItem itemValue="f" itemLabel="Femenino"/>
                                        </h:selectOneMenu>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="fechaNacimiento">Fecha de nacimiento:</label>
                                    <div class="space-10"></div>
                                    <p:datePicker  id="fechaNacimiento" value="#{usuarioBean.usuario.fechaNacimiento}" required="true" requiredMessage="Seleccione su fecha de nacimiento" showIcon="true" maxdate="#{usuarioBean.fechaActual}" pattern="dd-MM-yyyy"/>
                                    <div class="space-10"></div>
                                    <h:message for="fechaNacimiento" style="color:red"></h:message>
                                </div>
                                <div class="form-group">
                                    <label for="email">Correo electrónico:</label>
                                    <h:inputText  validatorMessage="La dirección de correo electrónico no es válida" pt:placeholder="Correo electrónico" id="email" styleClass="single-input-secondary" value="#{usuarioBean.usuario.email}" required="true" requiredMessage="Ingrese su dirección de correo electrónico">
                                        <f:validateRegex pattern="^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$"></f:validateRegex>
                                    </h:inputText>
                                    <h:message for="email" style="color:red"></h:message>
                                </div>

                                <div class="form-group">
                                    <label for="password">Contraseña:</label>
                                    <h:inputSecret validatorMessage="La contraseña debe tener entre 8 y 16 caracteres, al menos un dígito, al menos una minúscula y al menos una mayúscula. No puede tener otra clase de símbolos." pt:placeholder="Contraseña" id="password" styleClass="single-input-secondary" value="#{usuarioBean.usuario.password}" required="true" requiredMessage="Ingrese una contraseña para su cuenta">
                                        <f:validateRegex pattern="^(?=\w*\d)(?=\w*[A-Z])(?=\w*[a-z])\S{8,16}$"></f:validateRegex>
                                    </h:inputSecret>
                                    <h:message for="password" style="color:red"></h:message>
                                </div>

                                <h:commandButton styleClass="btn_1" value="Registrarme" action="#{usuarioBean.insertarUsuario()}">
                                    <f:ajax execute="@form" render="registroForm"/>
                                </h:commandButton>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </ui:define>

    <ui:define name='scripts'>
        <h:outputScript library="js" name="jquery.magnific-popup.js" />
        <h:outputScript library="js" name='jquery.nice-select.min.js'/>
        <h:outputScript>
            <c:if test="#{not empty flash.exito}" >
                alertify.success('#{flash.exito}');
            </c:if>
        </h:outputScript>
    </ui:define>
</ui:composition>