src/main/java/com/utils/Beans/ImagenBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utils.Beans;

import com.utils.Entities.ImagenesProductoEntity;
import com.utils.Entities.ProductosEntity;
import com.utils.Model.ImagenesModel;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import org.apache.commons.io.IOUtils;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

/**
 *
 * @author HP
 */
@Named(value = "imagenBean")
@RequestScoped
public class ImagenBean {

    @EJB
    private ImagenesModel imagenesModel;
    private ImagenesProductoEntity imagen = new ImagenesProductoEntity();
    private UploadedFile archivo;

    public ImagenBean() {
    }

    public void subirImagen() throws IOException {
        try {
            if (archivo != null) {

                imagen.setImagen(IOUtils.toByteArray(archivo.getInputstream()));

                if (imagenesModel.agregarImagen(imagen) > 0) {
                    System.out.println("vergon");
                } else {
                    //mensaje de error
                    System.out.println("ocurrio un error :v");
                }
                FacesMessage message = new FacesMessage("Succesful", archivo.getFileName() + " is uploaded.");
                FacesContext.getCurrentInstance().addMessage(null, message);
            } else {
                FacesMessage message = new FacesMessage("Error", "No sirve esto");
                FacesContext.getCurrentInstance().addMessage(null, message);
            }

        } catch (Exception ex) {
            FacesMessage message = new FacesMessage("Error", "No sirve esto");
            FacesContext.getCurrentInstance().addMessage(null, message);
            Logger.getLogger(ImagenBean.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public StreamedContent getImagenProducto() throws IOException {
        FacesContext context = FacesContext.getCurrentInstance();

        if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            return new DefaultStreamedContent();
        } else {
            try {
                int id = Integer.parseInt(context.getExternalContext().getRequestParameterMap().get("id"));
                this.imagen = imagenesModel.obtenerImagen(id);
                return new DefaultStreamedContent(new ByteArrayInputStream(this.imagen.getImagen()));
            } catch(Exception e)  {
                return new DefaultStreamedContent(this.getClass().getClassLoader().getResourceAsStream("default.jpg"));
            }
        }
    }

    public ImagenesProductoEntity getImagen() {
        return imagen;
    }

    public void setImagen(ImagenesProductoEntity imagen) {
        this.imagen = imagen;
    }

    public UploadedFile getArchivo() {
        return archivo;
    }

    public void setArchivo(UploadedFile archivo) {
        this.archivo = archivo;
    }

}

src/main/java/com/utils/Beans/LibreriasBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utils.Beans;

import com.utils.Entities.LibreriasEntity;
import com.utils.Model.LibreriasModel;
import com.utils.Utils.jsfUtil;
import com.utils.Utils.validation;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import com.utils.Utils.Utils;
import java.io.IOException;
import java.util.ArrayList;
import javax.annotation.PostConstruct;

/**
 *
 * @author Henry
 */
@Named(value = "libreriasBean")
@SessionScoped
public class LibreriasBean implements Serializable {

    @EJB
    private LibreriasModel libreriasModel;
    private LibreriasEntity libreria = new LibreriasEntity();
    List<LibreriasEntity> listaLibrerias;
    List<LibreriasEntity> listaFiltradaLibrerias;
    private List<String> listaDepartamentos;
    private List<String> listaMunicipios;

    public LibreriasBean() {
    }

    @PostConstruct
    public void init() {
        listaLibrerias = libreriasModel.listarLibrerias();
        listaMunicipios = new ArrayList<>();
    }

    public void listarLibreriasPorDepartamento() {
        if (libreria.getDepartamento().equals("-1")) {
            listaLibrerias = libreriasModel.listarLibrerias();
        } else {
           
            listaLibrerias = libreriasModel.listarLibreriasPorDepartamento(libreria.getDepartamento());
            
        }
    }
    
    public void listarLibreriasPorMunicipio() {
        if (libreria.getMunicipio().equals("-1")) {
            listaLibrerias = libreriasModel.listarLibreriasPorDepartamento(libreria.getDepartamento());
        } else {
            
            listaLibrerias = libreriasModel.listarLibreriasPorMunicipio(libreria.getMunicipio());
        }
    }
    
    public void listarLibreriasPorNombre(){
        if(libreria.getNombre().trim().equals("")){
            listaLibrerias = libreriasModel.listarLibrerias();
        }else{
            
            listaLibrerias = libreriasModel.listarLibreriasPorNombre(libreria.getNombre());
        }
        
    }
    
    public void seleccionarLibreria(String codigo) throws IOException{
        this.libreria = libreriasModel.obtenerLibreria(codigo);
        FacesContext.getCurrentInstance().getExternalContext().redirect("detallesLibreria.xhtml"); 
    }
    
    public void seleccionarLibreriaAdministrador(String codigo) throws IOException{
        this.libreria = libreriasModel.obtenerLibreria(codigo);
        FacesContext.getCurrentInstance().getExternalContext().redirect("../librerias/detalles.xhtml"); 
    }
    
    public List<LibreriasEntity> getListaLibrerias() {
        return listaLibrerias;
    }

    public List<String> getListaDepartamentos() {
        listaDepartamentos = libreriasModel.listarDepartamentos();
        return listaDepartamentos;
    }
    
    public void setListaMunicipios(String departamento){
        listaMunicipios = libreriasModel.listarMunicipios(departamento);
    }
    
    public List<String> getListaMunicipios(){
        return listaMunicipios;
    }

    public LibreriasEntity getLibreria() {
        return libreria;
    }

    public void setLibreria(LibreriasEntity libreria) {
        this.libreria = libreria;
    }

    public void agregarLibreria() {
        libreria.setIdLibreria(Utils.generarCodigo());
        libreria.setTelefono("-");
        libreria.setEmail("-");
        if (libreriasModel.agregarLibreria(libreria) > 0) {
            FacesContext.getCurrentInstance().getExternalContext().getFlash().put("success", "Libreria agregada exitossamente");
            libreria = new LibreriasEntity();
        } else {
            FacesContext.getCurrentInstance().getExternalContext().getFlash().put("error", "Ocurrio un error al momento de agregar la libreria");
        }
    }

    public String modificarLibreria() {
        if (libreriasModel.modificarLibreria(libreria) > 0) {
            //FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Registrado exitosamente!"));
            FacesContext.getCurrentInstance().getExternalContext().getFlash().put("success", "Libreria modificada exitossamente");
            libreria = new LibreriasEntity();
            return "/librerias/GestionarLibrerias?faces-redirect=true";
        } else {
            FacesContext.getCurrentInstance().getExternalContext().getFlash().put("error", "Ocurrio un error a la hora de modificar");
            return null;
        }
    }

    public String obtenerLibreria(String codigo) {
        libreria = libreriasModel.obtenerLibreria(codigo);
        return "/librerias/ModificarLibreria?faces-redirect=true";
    }

    public String eliminarLibreria(String codigo) {

        if (libreriasModel.eliminarLibreria(codigo) > 0) {
            //Mensaje
        }

        return null;
    }

    public List<LibreriasEntity> getListaFiltradaLibrerias() {
        return listaFiltradaLibrerias;
    }

    public void setListaFiltradaLibrerias(List<LibreriasEntity> listaFiltradaLibrerias) {
        this.listaFiltradaLibrerias = listaFiltradaLibrerias;
    }
    
    
}

src/main/webapp/search/_imagenProducto.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Imagen Producto</title>
        <h:outputStylesheet library="css" name="multizoom.css"/>
        <h:outputStylesheet library="css" name="main.css"/>
    </h:head>
    <h:body style="overflow: hidden;">
        <div class="center-left">
            <p:graphicImage value="#{imagenBean.imagenProducto}" id="image1" class="imagen-producto">
                <f:param name="id" value="#{productosBean.producto.imagenesProductoEntity.idImagen}"/>
            </p:graphicImage> 
        </div>
        <h:outputScript library="js" name="jquery-1.12.1.min.js"/>
        <h:outputScript library="js" name="multizoom.js"/>
        <h:outputScript library="js" name="multizoom-image.js"/>
    </h:body>
</html>

src/main/webapp/search/comparador.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/landig-layout-base.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="titulo">
        Comparador de productos entre distintas librerías
    </ui:define>

    <ui:define name="contenido">
        <section class="special_cource padding_top">
            <div class="container">
                <div class="row">
                    <h1>Comparador de precios</h1>
                </div>
                <div class="row">
                    <h4>Seleccione las librerías con las que desea comparar el precio del producto: #{productosBean.producto.nombre}</h4>
                </div>
                <div class="row">
                    <h:form prependId="false" id="comparadorForm">
                        <label for="selectLibrerias">Lista de librerías</label>
                        <br />
                        <p:selectCheckboxMenu id="selectLibrerias" value="#{productosBean.libreriasComparacion}" style="width:800px;" multiple="true" required="true" requiredMessage="Seleccione por lo menos una librería para efectuar la comparación."
                                              filter="true" filterMatchMode="startsWith" panelStyle="width:800px;">
                            <f:selectItems value="#{productosBean.listaPreciosProducto}" var="l" itemLabel="#{l.idLibreria.nombre}" itemValue="#{l.idLibreria.idLibreria}"/>
                        </p:selectCheckboxMenu>
                        <br />
                        <h:message for="selectLibrerias" errorStyle="color:red;"/>
                        <br /><br />
                        <h:commandButton value="Comparar" action="#{productosBean.comparacionPersonalizada()}">
                            <f:ajax execute="@form" render="comparadorForm comparacionPreciosForm tablaPrecios"/>
                        </h:commandButton>
                    </h:form>
                </div>
                <div class="space-30"></div>
                <div class="row">
                    <h:form id="comparacionPreciosForm">
                        <p:dataView var="p" value="#{productosBean.listaPersonalizada}" rows="12" paginator="true" rowsPerPageTemplate="12,16,20"
                                    paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                    id="tablaPrecios" rendered="#{productosBean.listaPersonalizada != null}">
                            <p:dataViewListItem>
                                <h:panelGrid columns="3" style="width:100%" columnClasses="logo,detail">
                                    <p:outputPanel>
                                        <h:panelGrid columns="2" cellpadding="5">
                                            <h:outputText value="Precio ($):" />
                                            <h:outputText value="$ #{p.precio}" style="font-weight: bold"/>
                                            <h:outputText value="Librería:" />
                                            <h:outputText value="#{p.idLibreria.nombre}" style="font-weight: bold"/>
                                            <h:outputText value="Departamento:" />
                                            <h:outputText value="#{p.idLibreria.departamento}" style="font-weight: bold"/>
                                            <h:outputText value="Municipio:" />
                                            <h:outputText value="#{p.idLibreria.municipio}" style="font-weight: bold"/>
                                            <h:commandButton action="#{libreriasBean.seleccionarLibreria(p.idLibreria.idLibreria)}" class="btn_4" value="Ver detalles de librería"/>
                                        </h:panelGrid>
                                    </p:outputPanel>

                                </h:panelGrid>
                            </p:dataViewListItem>
                        </p:dataView>

                    </h:form>
                </div>
            </div>
        </section>     
    </ui:define>

</ui:composition>

src/main/webapp/search/detallesLibreria.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/landig-layout-base.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns="http://www.w3.org/1999/xhtml">

    <ui:define name="titulo">
        Detalles de librería
    </ui:define>

    <ui:define name="contenido">
        <section class="blog_area section_padding">
            <div class="container">
                <div class="row align-items-sm-center align-items-lg-stretch">
                    <div class="col-md-7 col-lg-7">
                        <div class="learning_img">
                            <h:graphicImage library="img" name="learning_img.png"/>
                        </div>
                    </div>
                    <div class="col-md-5 col-lg-5">
                        <div class="learning_member_text">
                            <h3>Datos de librería:</h3>
                            <div class="space-10"></div>
                            <h4><h:outputText value="#{libreriasBean.libreria.nombre}"/></h4>
                            <div class="space-10"></div>
                            <h5>| Departamento:</h5> 
                            <p><h:outputText value="#{libreriasBean.libreria.departamento}"/></p>
                            <div class="space-10"></div>
                            <h5>| Municipio:</h5> 
                            <p><h:outputText value="#{libreriasBean.libreria.municipio}"/></p>
                            <div class="space-10"></div>
                            <h5>| Dirección: </h5>
                            <p><h:outputText value="#{libreriasBean.libreria.direccion}"/></p>
                            <div class="space-10"></div>
                            <h5>| Cantidad de productos que ofrece: </h5>
                            <p><h:outputText value="#{libreriasBean.libreria.libreriaProductoEntityList.size()}"/></p>
                        </div>
                    </div>
                </div>
                <div class="space-50"></div>
                <div class="row">
                    <div class="col-md-6">
                        <h2>Conoce sus productos</h2>
                    </div>
                </div>
                <div class="space-30"></div>
                <div class="row">
                    <h:form prependId="false" id="listadoProductosForm" class="col-md-12">
                        <p:dataGrid var="p" value="#{productosBean.listarProductosPorLibreria(libreriasBean.libreria.idLibreria)}" columns="3" layout="grid"
                                    rows="9" paginator="true" emptyMessage="Esta librería aun no posee productos"
                                    paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                    rowsPerPageTemplate="9,12,15" 
                                    id="tablaProductos">

                            <p:panel style="margin:15px 0px;">
                                <h:panelGrid columns="1" style="width:100%;">
                                    <div class="col-md-4">
                                        <div class="single_special_cource">
                                            <p:graphicImage value="#{imagenBean.imagenProducto}" class="detalle-imagen">
                                                <f:param name="id" value="#{p.imagenesProductoEntity.idImagen}"/>
                                            </p:graphicImage>  
                                            <div class="special_cource_text">
                                                <div class="space-10"></div>
                                                <h:commandButton action="#{productosBean.obtenerProducto(p.idProducto)}" class="btn_4" value="Detalles"/>
                                                <div class="space-10"></div>
                                                <div class="typography">
                                                    <h5>#{p.nombre}</h5>
                                                    <h6><span class="bold">Categoría:</span> #{p.idCategoria.nombre}</h6>
                                                </div>
                                                <div class="linea"></div>
                                                <div>
                                                    <h6>Cantidad de precios encontrados: #{p.libreriaProductoEntityList.size()}</h6>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </h:panelGrid>
                            </p:panel>
                        </p:dataGrid>    
                    </h:form>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <h:link value="Regresar" outcome="librerias" styleClass="genric-btn primary radius"/>
                    </div>
                </div>
            </div>
        </section> 
    </ui:define>

    <ui:define name="scripts">

    </ui:define>

</ui:composition>

src/main/webapp/search/graficador.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/landig-layout-base.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <ui:define name="titulo">
        Graficador
    </ui:define>

    <ui:define name="contenido">
        #{loginBean.sesionRequerida()}
        
        <section class="advance_feature learning_part">
            <div class="container">
                <div class="row align-items-sm-center align-items-xl-stretch">
                    <div class="col-md-6 col-lg-6">
                        <h2>Generación de gráficos</h2>
                    </div>
                </div>
                <div class="space-30"></div>
                <div class="row">
                    <h5>El presente gráfico detalla las diferencias de precios que existen para el producto <b>#{productosBean.producto.nombre}</b> en las distintas librerías </h5>
                    <c:if test='#{productosBean.libreriaProducto.idLibreria.departamento == "-1" and productosBean.libreriaProducto.idLibreria.municipio == "-1"}'>
                        <h5>ubicadas en todo el país de El Salvador.</h5>
                    </c:if>
                    <c:if test='#{productosBean.libreriaProducto.idLibreria.departamento != "-1" and productosBean.libreriaProducto.idLibreria.municipio == "-1"}'>
                        <h5>ubicadas en el departamento de #{productosBean.libreriaProducto.idLibreria.departamento}.</h5>
                    </c:if>
                    <c:if test='#{productosBean.libreriaProducto.idLibreria.departamento != "-1" and productosBean.libreriaProducto.idLibreria.municipio != "-1"}'>
                        <h5>ubicadas en el municipio de #{productosBean.libreriaProducto.idLibreria.municipio} del departamento de #{productosBean.libreriaProducto.idLibreria.departamento}.</h5>
                    </c:if>
                    <h5></h5>
                </div>
                <div class="row">
                    <h:panelGrid id="contenedor-grafico-barras" class="center-all" rendered="#{productosBean.barra != null}">
                        <div>
                            <p:chart type="bar" model="#{productosBean.barra}" style="width:800px; height:600px;" widgetVar="graficoBarra"/>
                        </div> 
                        <div class="col-md-4">
                            <div class="mb-20"></div>
                            <h:button value="Exportar" class="genric-btn info small" onclick="return exportChartInPDF('graficoBarra', '#{productosBean.producto.nombre}', '#{productosBean.libreriaProducto.idLibreria.departamento}', '#{productosBean.libreriaProducto.idLibreria.municipio}');" rendered="#{productosBean.barra != null}"/>
                        </div>
                    </h:panelGrid>
                </div>
                <div class="space-30"></div>
                <div class="row">
                    <div class="col-md-4">
                        <h:link value="Regresar" outcome="productos" class="genric-btn primary radius"/>
                    </div>
                </div>
            </div>
        </section>
    </ui:define>

    <ui:define name="scripts">
        <h:outputScript library="js" name="pdfmake.min.js"/>
        <h:outputScript library="js" name="vfs_fonts.js"/>
        <h:outputScript library="js" name="export.js"/>
    </ui:define>
</ui:composition>

src/main/webapp/search/probandohistorial.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        
        <h:form>
            <p>Agregar historial del usuario actual</p>
            
            <h:commandButton action="#{historialBean.agregarHistorial()}"></h:commandButton>
        </h:form>
        
    </h:body>
</html>

src/main/webapp/search/productos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/landig-layout-base.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns="http://www.w3.org/1999/xhtml">

    <ui:define name="titulo">
        Productos
    </ui:define>

    <ui:define name="contenido">
        <section class="special_cource padding_top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="blog_right_sidebar">
                            <h:form prependId="false">
                                <aside class="single_sidebar_widget search_widget">
                                    <div class="form-group">
                                        <div class="input-group mb-3">
                                            <h:inputText class="form-control" id="nombreProducto" value="#{productosBean.producto.nombre}" pt:placeholder="Busca un producto"/>
                                            <div class="input-group-append">
                                                <button class="btn" type="button"><i class="ti-search"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                    <h:commandButton class="button rounded-0 primary-bg text-white w-100 btn_1" value="Buscar" action="#{productosBean.listarProductosPorNombre()}">
                                        <f:param name="idUsuario" id="idUsuario" value="#{loginBean.usuario.idUsuario}"/>
                                        <f:ajax execute="@form" render="tablaProductos"/>
                                    </h:commandButton>
                                </aside>
                                <aside class="single_sidebar_widget post_category_widget">
                                    <h4 class="widget_title">Categorías</h4>
                                    <div class="single-element-widget mt-30">
                                        <div class="default-select" id="default-select">
                                            <h:selectOneMenu value="#{productosBean.producto.idCategoria.idCategoria}" class="nice-select">
                                                <f:selectItem  itemValue="0" itemLabel="Todas"/>
                                                <f:selectItems value="#{categoriasBean.listaCategorias}" var="c" itemLabel="#{c.nombre}" itemValue="#{c.idCategoria}"/>
                                                <f:ajax event="change" listener="#{productosBean.listarProductosPorCategoria()}" render="listadoProductosForm tablaProductos"/>
                                            </h:selectOneMenu>
                                        </div>
                                    </div>
                                </aside>
                            </h:form>
                        </div>
                    </div>
                    <div class="col-lg-9 mb-5 mb-lg-0">
                        <div class="blog_left_sidebar">
                            <article class="blog_item">
                                <h:form prependId="false" id="listadoProductosForm">
                                    <p:dataGrid var="p" value="#{productosBean.listaProductos}" columns="3" layout="grid"
                                                rows="9" paginator="true" emptyMessage="No se encontraron resultados para su búsqueda"
                                                paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                                rowsPerPageTemplate="9,12,15" 
                                                id="tablaProductos">

                                        <p:panel style="margin:15px 0px;">
                                            <h:panelGrid columns="1" style="width:100%;">
                                                <div class="col-md-4">
                                                    <div class="single_special_cource">
                                                        <p:graphicImage value="#{imagenBean.imagenProducto}" class="detalle-imagen">
                                                            <f:param name="id" value="#{p.imagenesProductoEntity.idImagen}"/>
                                                        </p:graphicImage>  
                                                        <div class="special_cource_text">
                                                            <div class="space-10"></div>
                                                            <h:commandButton action="#{productosBean.obtenerProducto(p.idProducto)}" class="btn_4" value="Detalles"/>
                                                            <div class="space-10"></div>
                                                            <div class="typography">
                                                                <h5>#{p.nombre}</h5>
                                                                <h6><span class="bold">Categoría:</span> #{p.idCategoria.nombre}</h6>
                                                            </div>
                                                            <div class="linea"></div>
                                                            <div>
                                                                <h6>Cantidad de precios encontrados: #{p.libreriaProductoEntityList.size()}</h6>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </h:panelGrid>
                                        </p:panel>
                                    </p:dataGrid>    
                                </h:form>
                            </article>
                        </div>
                    </div>
                </div>
            </div>
        </section>    
    </ui:define>

    <ui:define name="scripts">

    </ui:define>

</ui:composition>